#!/bin/bash
# =============================================================================
# Auto-Test-Plan Generator
# =============================================================================
# Purpose: Automatically generate test plans from User Story acceptance criteria
# Usage: bash scripts/auto-test-plan.sh US-XXX
#
# This script parses User Story files and generates test cases based on
# acceptance criteria. Saves hours of manual test plan creation.
#
# Time: ~2 minutes vs 20+ minutes manual
# =============================================================================

set -e  # Exit on error

US_FILE="$1"
US_ID=$(echo "$US_FILE" | grep -oP 'US-\d+' || echo "")

if [ -z "$US_ID" ]; then
    echo "❌ Error: Invalid User Story ID. Usage: bash scripts/auto-test-plan.sh US-XXX"
    exit 1
fi

# Find the actual file if just ID provided
if [ ! -f "$US_FILE" ]; then
    # Search for the file
    US_FILE=$(find docs/agile_framework/05_user_stories -name "${US_ID}_*.md" 2>/dev/null | head -1)
    if [ -z "$US_FILE" ]; then
        echo "❌ Error: User Story file not found for $US_ID"
        exit 1
    fi
fi

echo "# 🧪 Test Plan: TEST-$US_ID"
echo ""
echo "**User Story:** $US_ID"
echo "**Generated:** $(date '+%Y-%m-%d %H:%M:%S')"
echo "**Generated by:** Auto-Test-Plan Generator"
echo ""

# Extract metadata
TITLE=$(grep -m1 '^# ' "$US_FILE" | sed 's/^# //' || echo "Unknown")
echo "**Feature Name:** $TITLE"
echo ""

# =============================================================================
# Section 1: Test Cases from Acceptance Criteria
# =============================================================================

echo "## Test Cases (Auto-Generated from Acceptance Criteria)"
echo ""

# Find Acceptance Criteria section
ACCEPTANCE_START=$(grep -n "## Acceptance Criteria" "$US_FILE" | cut -d: -f1)
if [ -z "$ACCEPTANCE_START" ]; then
    echo "❌ Error: Acceptance Criteria section not found in User Story"
    exit 1
fi

# Extract acceptance criteria (start from section, go until next ## or end)
CRITERIA=$(tail -n +"$((ACCEPTANCE_START + 1))" "$US_FILE" | sed -n '/^## /q;p')

# Count criteria
COUNT=1
echo "$CRITERIA" | while IFS= read -r line; do
    # Skip empty lines and non-criteria lines
    if [[ -z "$line" ]] || [[ ! "$line" =~ ^[-*] ]]; then
        continue
    fi

    # Extract criterion text
    CRITERION_TEXT=$(echo "$line" | sed 's/^[-*]\s*\[\s*.\?\s*\]\s*//' | sed 's/^\*\*//' | sed 's/\*\*$//')

    if [ -n "$CRITERION_TEXT" ]; then
        echo "### Test Case $COUNT: $CRITERION_TEXT"
        echo ""
        echo "**Scenario:** Verify $CRITERION_TEXT"
        echo ""
        echo "**Steps:**"
        echo "1. [To be defined by QA based on feature]"
        echo ""
        echo "**Expected Result:** $CRITERION_TEXT"
        echo ""
        echo "**Status:** [ ] Not Tested"
        echo ""
        echo "---"
        echo ""
        COUNT=$((COUNT + 1))
    fi
done

# =============================================================================
# Section 2: Standard Test Cases
# =============================================================================

echo "## Standard Test Cases"
echo ""

echo "### Test Case: Security - XSS Prevention"
echo ""
echo "**Scenario:** Ensure all user input is properly escaped"
echo ""
echo "**Steps:**"
echo "1. Enter HTML tags in text fields"
echo "2. Submit form"
echo "3. View output"
echo ""
echo "**Expected Result:** HTML tags are displayed as text, not rendered"
echo ""
echo "**Status:** [ ] Not Tested"
echo ""
echo "---"
echo ""

echo "### Test Case: Security - CSRF Protection"
echo ""
echo "**Scenario:** Ensure forms include CSRF tokens"
echo ""
echo "**Steps:**"
echo "1. View page source"
echo "2. Search for CSRF token field"
echo ""
echo "**Expected Result:** CSRF token field present in all forms"
echo ""
echo "**Status:** [ ] Not Tested"
echo ""
echo "---"
echo ""

echo "### Test Case: Dark Mode Support"
echo ""
echo "**Scenario:** Verify feature works in dark mode"
echo ""
echo "**Steps:**"
echo "1. Switch to dark mode"
echo "2. Verify all elements visible"
echo "3. Check color contrast"
echo ""
echo "**Expected Result:** Feature renders correctly in dark mode"
echo ""
echo "**Status:** [ ] Not Tested"
echo ""
echo "---"
echo ""

echo "### Test Case: Mobile Responsiveness"
echo ""
echo "**Scenario:** Verify feature works on mobile devices"
echo ""
echo "**Steps:**"
echo "1. Resize browser to mobile viewport (< 768px)"
echo "2. Verify layout adapts"
echo "3. Check touch interactions"
echo ""
echo "**Expected Result:** Feature is fully functional on mobile"
echo ""
echo "**Status:** [ ] Not Tested"
echo ""
echo "---"
echo ""

echo "### Test Case: Error Handling"
echo ""
echo "**Scenario:** Verify graceful error handling"
echo ""
echo "**Steps:**"
echo "1. Submit invalid data"
echo "2. Submit empty required fields"
echo "3. Check error messages"
echo ""
echo "**Expected Result:** Appropriate error messages displayed"
echo ""
echo "**Status:** [ ] Not Tested"
echo ""

# =============================================================================
# Section 3: Test Execution Checklist
# =============================================================================

echo "## Test Execution Checklist"
echo ""

echo "### Pre-Test Setup"
echo "- [ ] Test environment prepared"
echo "- [ ] Test data available"
echo "- [ ] Browser(s) ready (Chrome, Firefox, Safari)"
echo "- [ ] Mobile viewport available"
echo ""

echo "### During Testing"
echo "- [ ] Document actual results"
echo "- [ ] Capture screenshots of issues"
echo "- [ ] Note any deviations from expected results"
echo ""

echo "### Post-Test"
echo "- [ ] All test cases executed"
echo "- [ ] Bugs logged (if any found)"
echo "- [ ] Test report completed"
echo ""

# =============================================================================
# Instructions for QA
# =============================================================================

echo "## 📝 QA Instructions"
echo ""

echo "**Manual Testing Required:**"
echo "- This test plan was auto-generated from acceptance criteria"
echo "- Fill in detailed test steps based on actual feature implementation"
echo "- Execute each test case and document results"
echo "- Create bug reports for any failures"
echo ""

echo "**Test Results Location:**"
echo "- Save test report to: \`docs/agile_framework/04_testing/test_reports/TEST-${US_ID}_report.md\`"
echo "- Log bugs to: \`docs/agile_framework/04_testing/bug_reports/\`"
echo ""

echo "**Notes:**"
echo "- Adapt test steps based on actual implementation"
echo "- Add edge cases as needed"
echo "- Remove irrelevant test cases"
echo "- Update expected results if acceptance criteria changed"
